config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Defines the root path route ("/")
  root to: 'public_recipes#index'

  resources :users, only: %i[index]
  resources :recipes, only: %i[index show new create destroy]
  resources :foods, only: %i[index new create destroy]
  resources :recipes_foods, only: %i[new create]
  resources :public_recipes, only: %i[index]
  resources :recipes_foods, only: %i[new create destroy]
  resources :shopping_lists, only: %i[index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    can :manage, Recipe, user_id: user.id
    can :manage, Food, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipes_foods, dependent: :destroy
  has_and_belongs_to_many :recipes, join_table: :recipes_foods

  validates :name, presence: true, length: { maximum: 30 }
  validates :measurement_unit, presence: true, length: { maximum: 10 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipes_foods, dependent: :destroy
  has_and_belongs_to_many :foods, join_table: :recipes_foods

  validates :name, presence: true, length: { maximum: 30 }
  validates :description, presence: true, length: { minimum: 20 }
  validates :cooking_time, presence: true, numericality: { greater_than: 0 }
  validates :preparation_time, presence: true, numericality: { greater_than: 0 }
  validates :public, inclusion: { in: [true, false] }

  def total_value(recipe)
    @total_value = 0
    @recipes_foods = RecipesFood.where(recipe_id: recipe)
    @recipes_foods.each do |item|
      @food = Food.find(item.food_id)
      @total_value += @food.price * item.quantity
    end
    @total_value
  end
end

app/models/recipes_food.rb
class RecipesFood < ApplicationRecord
  has_many :foods
  has_many :recipes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :foods
  has_many :recipes

  validates :name, presence: true, length: { maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = Food.where(user: current_user)
  end

  def new
    @food = Food.new
  end

  def create
    food = Food.new(params.require(:food).permit(:name, :measurement_unit, :price, :quantity))
    food.user = current_user

    if food.save
      flash[:success] = 'Ingredient added successfully'
    else
      flash.now[:error] = 'Error: Ingredient could not be added'
    end
    redirect_to foods_path
  end

  def destroy
    Food.destroy(params[:id])
    flash[:notice] = 'Food deleted'
    redirect_to foods_path
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.includes([:user]).where(public: true)
      .or(Recipe.includes([:user]).where(user: current_user)).order(updated_at: :desc)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.where(user: current_user)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipes_foods = RecipesFood.where(recipe_id: params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      flash[:notice] = 'Recipe created'
      redirect_to recipes_path
    else
      flash[:alert] = @recipe.errors.full_messages.join(', ')
      redirect_to new_recipe_path
    end
  end

  def destroy
    Recipe.destroy(params[:id])
    flash[:notice] = 'Recipe deleted'
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public)
  end
end

app/controllers/recipes_foods_controller.rb
class RecipesFoodsController < ApplicationController
  before_action :authenticate_user!

  def new
    @foods = Food.where(user: current_user)
    @recipes_food = RecipesFood.new
  end

  def create
    if RecipesFood.where(food_id: params[:recipes_food][:food_id], recipe_id: params[:recipes_food][:recipe_id]).exists?
      flash[:alert] = 'Ingredient already added to recipe'
      redirect_to recipe_path(params[:recipes_food][:recipe_id])
    else
      recipes_food = RecipesFood.new
      recipes_food.recipe_id = params[:recipes_food][:recipe_id]
      recipes_food.food_id = params[:recipes_food][:food_id]
      recipes_food.quantity = params[:recipes_food][:quantity]
      if recipes_food.save
        flash[:notice] = 'Ingredient added to recipe'
        redirect_to recipe_path(recipes_food.recipe_id)
      else
        flash[:alert] = 'Ingredient couldn\'t be added to recipe'
        render :new
      end
    end
  end

  def destroy
    recipes_food = RecipesFood.find(params[:id])
    recipes_food.destroy
    flash[:notice] = 'Ingredient removed successfully'
    redirect_to recipe_path(recipes_food.recipe_id)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipe = Recipe.find(params[:format])
    @total = total_value
  end

  def total_value
    @total_value = 0
    @recipes_foods = RecipesFood.where(recipe_id: params[:format])
    @recipes_foods.each do |item|
      @food = Food.find(item.food_id)
      @total_value += @food.price * item.quantity
    end
    @total_value
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<div class="recipe-details bg-gradient-to-b from-blue/75 to-blueD bg-fixed flex flex-col w-full min-h-screen bg-slate-200 items-center gap-4 p-[2%]">
  <div class="flex justify-between items-center w-[90%] sm:w-[40%]">
    <h1 class="text-3xl font-semibold font-pacifico italic mt-4 text-yellowL sm:text-6xl sm:mb-8">Food List</h1>
    <%= link_to "Add Food", new_food_path,
      class: "px-4 py-2 text-white hover:text-yellow font-semibold sm:text-xl
      hover:shadow-lg hover:bg-black hover:bg-black/30 ease-in-out duration-300
      rounded-md" %>
  </div>

  <table class="table-auto border-spacing-2 text-white sm:text-xl">
    <thead class="border border-black bg-black/40">
      <tr class = "border border-black">
        <th class = "border border-black px-4 font-semibold sm:p-4">Food</th>
        <th class = "border border-black px-4 font-semibold sm:p-4">Measurement Unit</th>
        <th class = "border border-black px-4 font-semibold sm:p-4">Unit Price</th>
        <th class = "border border-black px-4 font-semibold sm:p-4">Quantity</th>
        <th class = "border border-black px-4 font-semibold sm:p-4">Actions</th>
      </tr>
    </thead>
    <tbody class = "border border-black bg-black/10">
      <% @foods.each do |food| %>
        <tr class = "border border-black">
          <td class = "border border-black px-4"><%= food.name %></td>
          <td class = "border border-black px-4"><%= food.measurement_unit %></td>
          <td class = "border border-black px-4">$<%= food.price %></td>
          <td class = "border border-black px-4"><%= food.quantity %></td>
          <td class = "border border-black px-4">
            <%= button_to 'Remove', food_path(food), method: :delete,
              class: "px-2 py-1 hover:text-yellow hover:font-semibold
              hover:shadow-lg hover:bg-black hover:bg-black/30 ease-in-out duration-300
              rounded-md sm:text-xl sm:my-4 sm:px-4 sm:py-2" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<div class="new-ingredient flex flex-col items-center mx-auto pt-10">
  <h1 class = "text-3xl font-bold mb-4">Recipe App</h1>
  <h2 class = "text-2xl mb-4">Add a New Ingredient</h2>
  <%= form_with model: @food, url: foods_path, method: :post do |form| %>
    <div class = "mb-4">
      <%= form.text_field :name, placeholder: 'Ingredient Name', class: "rounded" %>
    </div>
    <div class = "mb-4">
      <%= form.text_field :measurement_unit, placeholder: 'Measurement Unit', class: "rounded" %>
    </div>
    <div class = "mb-4">
      <%= form.text_field :price, placeholder: 'Price', class: "rounded" %>
    </div>
    <div class = "mb-4">
      <%= form.text_field :quantity, placeholder: 'Quantity', class: "rounded" %>
    </div>
    <div class = "mt-6">
      <%= form.submit 'Add Food', class: 'cursor-pointer font-semibold rounded px-4 py-2 bg-cyan-300 hover:bg-cyan-700 hover:text-white' %>
    </div>
    <div class = "mt-4">
      <%= link_to "Cancel", :back, class: 'cursor-pointer font-semibold rounded px-4 py-2 bg-cyan-300 hover:bg-cyan-700 hover:text-white' %>  
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="nav-bar w-[100%] bg-blueD fixed z-10 shadow-lg shadow-yellow-600">
  <div class="nav-bar-content flex justify-between items-center w-[90%] mx-auto">
    <div class="logo">
      <img src="/logo.png" alt="logo" class="w-24 h-24 m-2 cursor-pointer">
    </div>
    <div class="nav-links">
      <ul class="desktop flex flex-col sm:flex-row">
        <li>
          <%= link_to "Home", root_path, class: "text-xl font-semibold text-white rounded py-1 px-4
            hover:text-yellow hover:shadow-lg hover:bg-black hover:bg-opacity-30 ease-in-out duration-300 rounded-md sm:py-3 sm:px-6" %>
        </li>
        <li>
          <%= link_to "Recipes", recipes_path, class: "text-xl font-semibold text-white rounded py-1 px-4
            hover:text-yellow hover:shadow-lg hover:bg-black hover:bg-opacity-30 ease-in-out duration-300 rounded-md sm:py-3 sm:px-6" %>
        </li>
        <li>
          <%= link_to "Foods", foods_path, class: "text-xl font-semibold text-white rounded py-1 px-4
            hover:text-yellow hover:shadow-lg hover:bg-black hover:bg-opacity-30 ease-in-out duration-300 rounded-md sm:py-3 sm:px-6" %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "load" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <% if current_user %>
      <%= button_to "[➥", destroy_user_session_path, method: :delete,
        class: 'absolute top-28 right-2 p-2 text-white font-bold hover:text-yellow
          hover:shadow-lg hover:bg-black hover:bg-black/30 ease-in-out duration-300
          rounded-md sm:text-xl lg:text-2xl xl:text-3xl sm:right-8
          lg:right-14 xl:right-20 2xl:right-28',
        title: 'Log-out'
      %>
      <p class="absolute top-28 left-4 text-white sm:text-lg lg:text-xl sm:left-16 lg:left-20 lg:top-32">
        Hello, <span class="font-semibold"><%= current_user.name %></span>
      </p>
    <% else %>
      <%= link_to "Log-in", new_user_session_path,
        class: 'absolute top-28 right-2 p-2 text-white font-semibold hover:text-yellow
          hover:shadow-lg hover:bg-black hover:bg-black/30 ease-in-out duration-300
          rounded-md lg:text-xl sm:right-8
          lg:right-14 xl:right-20 2xl:right-28',
        title: 'Logout'
      %>
      <p class="absolute top-28 left-4 text-white sm:text-lg lg:text-xl sm:left-16 lg:left-20 lg:top-32">
        Hello, <span class="font-semibold">Guest</span>
      </p>
    <% end %>
    <div class="w-screen pt-28 flex flex-col items-center">
      <% if flash[:notice] %>
        <p class="notice text-center bg-green-400 w-screen p-4 text-green-900 font-semibold"><%= notice %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert text-center bg-red-400 w-full p-4 text-red-900 font-semibold"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/public_recipes/index.html.erb
<div class="recipes bg-gradient-to-b from-blue/75 to-blueD bg-fixed flex flex-col w-full min-h-screen bg-slate-200 items-center gap-4 p-[2%]">
  <div class = "flex flex-row mb-4">
    <h1 class="text-3xl font-semibold font-pacifico italic mt-4 text-yellowL sm:text-6xl sm:mb-8">Public Recipes</h1>
  </div>
  <% @public_recipes.each do |recipe| %>
    <div class="recipe flex flex-row justify-between w-[90%] text-gray-700
      bg-gradient-to-b from-blueM to-blueL p-8 rounded-md hover:scale-105 ease-in-out duration-500
      hover:shadow-2xl hover:cursor-pointer hover:text-gray-900 sm:w-[64%] sm:text-xl"
    >
      <div>
        <%= link_to recipe_path(recipe) do %>
          <p class = "py-2 px-4 self-start hover:text-yellow hover:shadow-lg
            hover:bg-black hover:bg-black/30 ease-in-out duration-300
            rounded-md text-xl font-semibold sm:text-2xl">Recipe Name: <%= recipe.name %>
          </p>
        <% end %>
        <p class = "pl-6 self-start">By: <%= recipe.user.name %></p>
      </div>
      <div>
        <p class = "self-start">Total Food Items: <%= RecipesFood.where(recipe_id: recipe.id).count %></p>
        <p class = "self-start">Total Price: $<%= recipe.total_value(recipe.id) %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/index.html.erb
<div class="recipes bg-gradient-to-b from-blue/75 to-blueD bg-fixed flex flex-col w-full min-h-screen bg-slate-200 items-center gap-4 p-[2%]">
  <h1 class="text-3xl font-semibold font-pacifico italic mt-4 text-yellowL sm:text-6xl sm:mb-8">Recipes</h1>
  <%= link_to 'New Recipe', new_recipe_path, class: "self-end px-4 py-2 text-yellow font-bold text-lg
    hover:shadow-lg hover:bg-black hover:bg-black/30 ease-in-out duration-300
    rounded-md sm:mr-80" %>
  <% @recipes.each do |recipe| %>
    <div class="recipe flex flex-row justify-between w-[90%] text-gray-700
      bg-gradient-to-b from-blueM to-blueL p-8 rounded-md hover:scale-105 ease-in-out duration-500
      hover:shadow-2xl hover:cursor-pointer hover:text-gray-900 sm:w-[64%] sm:text-xl"
    >
      <div class="recipe-info flex self-start items-center gap-10">
        <%= link_to recipe_path(recipe) do %>
          <h2 class = "py-2 px-4 self-start hover:text-yellow hover:shadow-lg
              hover:bg-black hover:bg-black/30 ease-in-out duration-300
              rounded-md text-xl font-semibold sm:text-2xl"><%= recipe.name %>:
          <p class="mt-1 font-normal"><%= recipe.description %></p>
          </h2>
        <% end %>
      </div>
      <%= button_to 'Delete', recipe_path(recipe), method: :delete, class: "px-4 py-2 hover:text-yellow hover:font-bold text-lg
        hover:shadow-lg hover:bg-black hover:bg-black/30 ease-in-out duration-300 rounded-md" %>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="new-recipe flex flex-col items-center mx-auto mt-8">
  <h1 class = "text-3xl font-bold mb-4">Recipe App</h1>
  <h2 class = "text-2xl mb-4">Add a New recipe</h2>
  <%= form_with model: @recipe, url: recipes_path, method: :post do |form| %>
    <div class = "mb-4">
      <%= form.text_field :name, placeholder: 'Recipe Name', class: "rounded" %>
    </div>
    <div class = "mb-4">
      <%= form.text_area :description, placeholder: 'Description (min 20 chars)', class: "rounded" %>
    </div>
    <div class = "mb-4">
      <%= form.text_field :preparation_time, placeholder: 'Preparation Time (minutes)', class: "rounded" %>
    </div>
    <div class = "mb-4">
      <%= form.text_field :cooking_time, placeholder: 'Cooking Time (minutes)', class: "rounded" %>
    </div>
    <div class = "mb-4">
      <%= form.check_box :public %>
      <%= form.label :public, "Public" %>
    </div>
    <div class = "mt-6">
      <%= form.submit 'Create Recipe', class: 'cursor-pointer font-semibold rounded px-4 py-2 bg-cyan-300 hover:bg-cyan-700 hover:text-white' %>
    </div>
    <div class = "mt-6">
      <%= link_to "Cancel", recipes_path, class: 'cursor-pointer font-semibold rounded px-4 py-2 bg-cyan-300 hover:bg-cyan-700 hover:text-white' %>  
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="recipe-details bg-gradient-to-b from-blue/75 to-blueD bg-fixed flex flex-col w-full min-h-screen bg-slate-200 items-center gap-4 p-[2%]">
  <h1 class="text-3xl font-semibold font-pacifico italic mt-4 text-yellowL sm:text-6xl sm:mb-8">
    <%= @recipe.name %> Recipe
  </h1>
  <div class="recipe-details flex w-[90%] justify-between px-4 py-2 text-white sm:text-xl sm:w-[64%]">
    <div class="cooking-details space-y-4">
      <p class="flex flex-col space-x-2 sm:flex-row sm:items-baseline">
        <span class="font-semibold">Preparation time:</span>
        <span class="ml-2 sm:ml-0">
          <%= @recipe.preparation_time %> minutes
        </span>
      </p>
      <p class="flex flex-col space-x-2 sm:flex-row">
        <span class="font-semibold">Cooking time:</span>
        <span class="ml-2">
          <%= @recipe.cooking_time %> minutes
        </span>
      </p>
      <p>
        <%= @recipe.description %>
      </p>
    </div>
    <div class="status">
      <p>
        <span class="font-semibold">Status:</span>
        <%= "Public" if @recipe.public? %>
        <%= "Private" unless @recipe.public? %>
      </p>
    </div>
  </div>
  <div class="buttons w-[100%] flex flex-wrap space-y-2 justify-between items-baseline px-4 py-2 sm:text-xl sm:w-[64%]">
    <%= link_to "Generate Shopping List", shopping_lists_path(@recipe),
      class: "px-2 py-1 text-yellow font-semibold hover:shadow-lg bg-black/30 ease-in-out duration-300
      rounded-md sm:text-xl sm:my-4 sm:px-4 sm:py-2" %>
    <%= link_to "Add Ingredient", new_recipes_food_path(@recipe),
      class: "px-2 py-1 text-yellow font-semibold hover:shadow-lg bg-black/30 ease-in-out duration-300
      rounded-md sm:text-xl sm:my-4 sm:px-4 sm:py-2" %>
  </div>
  <hr class="border border-white w-[80%] sm:w-[55%] sm:m-4">
  <% if @recipe.recipes_foods.length > 0 %>
    <table class="table-auto border-spacing-2 text-white sm:text-xl">
      <thead class="border border-black bg-black/40">
        <tr class="border border-black">
          <th class="border border-black px-4 font-semibold sm:p-4">Food</th>
          <th class="border border-black px-4 font-semibold sm:p-4">Quantity</th>
          <th class="border border-black px-4 font-semibold sm:p-4">Value</th>
          <th class="border border-black px-4 font-semibold sm:p-4">Actions</th>
        </tr>
      </thead>
      <tbody class = "border border-black bg-black/10">
        <% @recipes_foods.each do |item| %>
          <tr class = "border border-black">
            <% food = Food.find(item.food_id) %>
            <td class = "border border-black px-4"><%= food.name %></td>
            <td class = "border border-black px-4"><%= item.quantity %> <%= food.measurement_unit %></td>
            <td class = "border border-black px-4">$<%= food.price * item.quantity %></td>
            <td class = "border border-black px-4">
              <%= button_to 'Remove', recipes_food_path(food.recipes_foods.first), method: :delete,
                class: "px-2 py-1 hover:text-yellow hover:font-semibold
                hover:shadow-lg hover:bg-black hover:bg-black/30 ease-in-out duration-300
                rounded-md sm:text-xl sm:my-4 sm:px-4 sm:py-2" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="text-xl sm:text-3xl">No ingredients added yet</p>
  <% end %>
  <%= link_to "Back", recipes_path,
    class: "px-4 py-2 text-white hover:text-yellow hover:font-semibold sm:text-xl
    hover:shadow-lg hover:bg-black hover:bg-black/30 ease-in-out duration-300
    rounded-md" %>
</div>

app/views/recipes_foods/new.html.erb
<div class="new-recipe flex flex-col items-center mx-auto mt-8">
  <h1 class = "text-3xl font-bold mb-4">Recipes</h1>
  <h2 class = "text-2xl mb-4">Add a New ingredient</h2>
  <%= form_with model: @recipes_food, url: recipes_foods_path, method: :post do |form| %>
    <div class = "mb-4">
      <%= form.label :food_id, "Select Food:", class: "mr-2" %>
      <%= form.collection_select :food_id, @foods, :id, :name, prompt: true, class: "rounded" %>
    </div>
    <div class = "mb-4">
      <%= form.text_field :quantity, placeholder: 'Quantity', class: "rounded" %>
    </div>
    <%= form.hidden_field :recipe_id, value: params[:format].to_i %>
    <div class = "mt-6">
      <%= form.submit 'Add', class: 'cursor-pointer font-semibold rounded px-4 py-2 bg-cyan-300 hover:bg-cyan-700 hover:text-white' %>
    </div>
    <div class = "mt-6">
      <%= link_to "Cancel", :back, class: 'cursor-pointer font-semibold rounded px-4 py-2 bg-cyan-300 hover:bg-cyan-700 hover:text-white' %>  
    </div>
  <% end %>
  <%= @params %>
</div>

app/views/shopping_lists/index.html.erb
<div class="recipe-details bg-gradient-to-b from-blue/75 to-blueD bg-fixed flex flex-col w-full min-h-screen bg-slate-200 items-center gap-4 p-[2%]">
  <h1 class="text-3xl font-semibold font-pacifico italic mt-4 text-yellowL sm:text-6xl sm:mb-8">
    <%= @recipe.name %> Shopping List
  </h1>
  <div class="shopping-list-info flex flex-col justify-between w-[90%] text-white mt-6 sm:flex-row sm:text-2xl sm:w-[64%] sm:mt-14">
    <p><strong>Amount of food items to buy:</strong> <%= @recipe.recipes_foods.length %></p>
    <p class="mt-4 sm:mt-0"><strong>Total value of food needed:</strong> $<%= @total %></p>
  </div>
  <hr class="border border-white m-10 w-[80%] sm:w-[55%]">
  <table class="table-auto border-spacing-2 text-white sm:text-xl">
    <thead class="border border-black bg-black/40">
      <tr class="border border-black">
        <th class="border border-black px-4 font-semibold sm:p-4">Food</th>
        <th class="border border-black px-4 font-semibold sm:p-4">Quantity</th>
        <th class="border border-black px-4 font-semibold sm:p-4">Price</th>
      </tr>
    </thead class = "border border-black">
    <tbody class = "border border-black bg-black/10">
      <% @recipes_foods.each do |item| %>
        <tr class = "border border-black">
          <% food = Food.find(item.food_id) %>
          <td class = "border border-black px-6 py-1 sm:py-4 sm:px-8"><%= food.name %></td>
          <td class = "border border-black px-6 py-1 sm:py-4 sm:px-8"><%= item.quantity %> <%= food.measurement_unit %></td>
          <td class = "border border-black px-6 py-1 sm:py-4 sm:px-8">$<%= food.price * item.quantity %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Back", recipe_path(@recipe),
    class: "px-4 py-2 text-white hover:text-yellow hover:font-semibold sm:text-xl
    hover:shadow-lg hover:bg-black hover:bg-black/30 ease-in-out duration-300
    rounded-md" %>
</div>

app/views/users/index.html.erb
<body>
  <div class = "flex flex-row">
    <h1 class="text-3xl mr-32 mb-8 font-bold underline">Recipe App Users</h1>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'rounded-full border-2 pl-2 pr-2 pt-2 pb-2 bg-slate-500 text-white'  %>
  </div>
  <% @users.each do |user| %>
    <p class = "self-start">User Name: <%= user.name %>, email: <%= user.email %></p>
  <% end %>
</body>